name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: run
      run: ./main.exe < sample_intermedio.inp > sample.out
    - name: comparar
      run: kompare sample_intermedio.cor sample.out
